from __future__ import annotations

DEFAULT_SHOT_INITIAL_CANDIDATES = 256
DEFAULT_SHOT_MAX_SIMULATIONS = 10000
DEFAULT_SHOT_TIME_LIMIT_SEC = 2.6
DEFAULT_SHOT_MAX_DEPTH = 1

SHOT_KEEP_RATIO = 0.5
SHOT_MIN_VISITS_PER_ACTION = 1

